### ISSUE TITLE
Incorrect Case frequency in the Transitions table

### ISSUE THREAD

**Issue by katelashkevich** [AutomatedProcessImprovement/waiting-time-analysis#40]
In the _Transitions_ table, "Case frequency" is calculated incorrectly. For instance, for the production process, the case frequency for the "Turning & Milling Q.C. - Turning & Milling Q.C." transition = 116/225 =  51.55%. 
In the interface, it is 0.44%.

**Comment by iharsuvorau** [comment]
@katelashkevich Pushed changes to both repositories: waiting-time-analysis and waiting-time-backend. The production service is updated. This is the result for Production.log: http://193.40.11.233/jobs/53d772b0-9cc1-11ed-b7a1-0242ac1e0002. Is it correct now?

**Comment by katelashkevich** [comment]
Yes, looks correct. Thank you!
Tested: success.
