### ISSUE TITLE
Error exit 1 for loan origination log

### ISSUE THREAD

**Issue by katelashkevich** [AutomatedProcessImprovement/waiting-time-analysis#46]
@iharsuvorau @PowerMaxZ 
When uploading particular logs, Kronos responds with an error: 

<img width="361" alt="Screenshot 2023-08-25 at 13 11 07" src="https://github.com/AutomatedProcessImprovement/waiting-time-analysis/assets/83600435/3483e2a0-03e8-4530-9a16-ae217a3e139a">

No analysis results are presented. 

Event logs for which this error occurs: 
1) [Loan Origination v2-Repaired.csv](https://github.com/AutomatedProcessImprovement/waiting-time-analysis/files/12438050/Loan.Origination.v2-Repaired.csv)
2) Original loan origination log, but it's too big to attach here (I can email it if necessary). 

We need to have it fixed before 5 Sept.

**Comment by iharsuvorau** [comment]
@katelashkevich I wouldn't agree (a) it's a bug, and (b) it's related to the analysis CLI tool. **Don't put spaces into column names**. Preprocess them earlier in your log processing pipeline. It was never a requirement for the CLI tool to accept any possible event log format. 

This repository isn't a good place for this issue. It belongs either to the front-end or back-end depending on where the event log pre-processing happens. I've never managed this project, so I don't know what decisions have been made before about use cases, input requirements, etc.

**Comment by marlondumas** [comment]
@PowerMaxZ -- let's accept we cannot parse column names with spaces.
Is there a relatively easy way to detect that there are spaces or special characters in the uploaded file and if so, to give an error message stating that "The headers of the event log can only contain alphanumeric characters, - and _ "?
